version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: ln_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lunanotes
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql